### ISSUE TITLE
Crash on startup MC 1.19.2

### ISSUE THREAD

**Issue by DemonSeedxp** [Fabricators-of-Create/Porting-Lib#100]
The setup is using
Minecraft 1.19.2
Fabric Loader Version 0.15.2
Porting lib tested 2.1.1303, 305, and 308

All versions I've tried crash with the same error that can be seen in these logs
[crash-2024-04-13_06.08.48-client.txt](https://github.com/Fabricators-of-Create/Porting-Lib/files/14967028/crash-2024-04-13_06.08.48-client.txt)
[crash-2024-04-13_06.04.44-client.txt](https://github.com/Fabricators-of-Create/Porting-Lib/files/14967042/crash-2024-04-13_06.04.44-client.txt)
[crash-2024-04-13_04.38.56-client.txt](https://github.com/Fabricators-of-Create/Porting-Lib/files/14967043/crash-2024-04-13_04.38.56-client.txt)

There is a bunch of other mods installed that can be seen in the logs, but from what I can tell the crashes didn't start until I installed sodium-fabric-mc1.19.2-0.4.4+build.18, so I don't know where the conflict really lies, here or sodium, but the logs indicate it's porting lib at fault, so idk.

If you need anything else just let me know  

Just for thoroughness here is the mod set exactly as I have them installed in the form of a modrinth [mrpack file 1.0.0.zip](https://github.com/Fabricators-of-Create/Porting-Lib/files/14967065/hypercube.1.0.0.zip)

**Comment by TropheusJ** [comment]
you need indium
