### ISSUE TITLE
Sinytra Connector breaks due to overlapping mixins

### ISSUE THREAD

**Issue by Cuttleguy** [Fabricators-of-Create/Porting-Lib#102]
Your mixins add features in forge but not in fabric, but when sinytra connector loads this, those mixins crash the game because those fields already exist. I suggest to check if Sinytra is installed, and if so, disable those mixins, or at least parts of them. If you are looking for a crash log, an issue is already open on their side: https://github.com/Sinytra/Connector/issues/74. Please consider adding this logic, it would allow mods like Hephaestus(which use this mod) to be forge compatible. I just feel like this is easier to fix here than there. Thank you very much!

**Comment by IThundxr** [comment]
Sinytra connector is not supported, any issues caused by using it should be handled by them.
