### ISSUE TITLE
Incompatible with mods that use custom shaders on Quilt 1.19.2?

### ISSUE THREAD

**Issue by verbina29** [Fabricators-of-Create/Porting-Lib#106]
Porting Lib seems to cause crashes on startup with any mod that uses a shader, like Requiem, Haema, and Sync. This only happens on Quilt, the two Fabric mods will load just fine with Porting Lib on Fabric. I've tested with Sync 4.3, Haema 1.10.4,  Requiem 2.0.0, and Porting Lib 2.1.1308, and Quilt Loader 0.26.0-beta.1. It also happens with Porting Lib 2.1.1298, at least with Sync.

[crash_sync.txt](https://github.com/Fabricators-of-Create/Porting-Lib/files/15286399/crash_sync.txt)
[crash_requiem.txt](https://github.com/Fabricators-of-Create/Porting-Lib/files/15286400/crash_requiem.txt)
[crash_haema.txt](https://github.com/Fabricators-of-Create/Porting-Lib/files/15286401/crash_haema.txt)

**Comment by IThundxr** [comment]
If this still occurs feel free to open a new issue
