### ISSUE TITLE
Incompatible with LabyMod

### ISSUE THREAD

**Issue by strich3** [Fabricators-of-Create/Porting-Lib#107]
Hey,

I was using the mods that had portinglib included a while ago and it worked great with labymod. Sadly it seems to be broken with LabyMod and I can‘t even start the game.
Here is my crash log:

https://paste.labymod.net/galewobisetejatiwuhe

**Comment by strich3** [comment]
Changing the value from `1` to `4` `modules/base/src/main/resources/porting_lib_base.mixins.json` in line 144 fixes the issue. I don't know if anything else breaks tho. But on my end everything still works

**Comment by strich3** [comment]
#108

**Comment by TropheusJ** [comment]
compatibility with invasive proprietary garbage will not be fixed
