### ISSUE TITLE
[Bug] player.getEntityReach() always returns 0

### ISSUE THREAD

**Issue by Karashok-Leo** [Fabricators-of-Create/Porting-Lib#116]
player.getEntityReach() always returns 0
Maybe it's because the attack range attribute is implemented additively.
https://github.com/JamiesWhiteShirt/reach-entity-attributes/issues/11

**Comment by IThundxr** [comment]
This is because porting lib's attributes aren't setup correctly, you should just use reach entity attributes over porting lib's attributes
