### ISSUE TITLE
crashes world

### ISSUE THREAD

**Issue by xXRICHARDSONXx** [Fabricators-of-Create/Porting-Lib#118]
the world crashes when interacting with some blocks, the error comes specifically when I add the supplementaries mod, MehVahdJukaar told me to report here

[latest.log](https://github.com/user-attachments/files/16075544/latest.log)

[crash-2024-07-02_02.31.44-client.txt](https://github.com/user-attachments/files/16075545/crash-2024-07-02_02.31.44-client.txt)

Fabric 1.20.1
these are my current mods
![image](https://github.com/Fabricators-of-Create/Porting-Lib/assets/153337546/61b852de-af65-4a80-a8db-4c62ba5d9363)

**Comment by TropheusJ** [comment]
This error makes no sense. Porting lib code is calling a porting lib method that somehow doesn't exist.
I can't reproduce this. If you still can, I need very specific steps on how to do so.
