### ISSUE TITLE
Farmer's Delight Refrabricated and Mr Crayfish's Furniture Mod Refurbished crash

### ISSUE THREAD

**Issue by SAPH3RE** [Fabricators-of-Create/Porting-Lib#120]
I was told to specifically bring the issue here as well, so here's the crash log of the incidence with porting lib.
[crash-2024-07-27_14.10.58-client.txt](https://github.com/user-attachments/files/16398814/crash-2024-07-27_14.10.58-client.txt)

**Comment by ChrysanthCow** [comment]
This was apparently fixed in this commit.
https://github.com/MrCrayfish/MrCrayfishFurnitureMod-Refurbished/commit/33423a8060d2d6927233ed38e7cad0850842a1e1

However, my guess is that the issue lies in Porting Lib's Recipe Book API not liking it when two mods implement it.

**Comment by TropheusJ** [comment]
What does this have to do with Porting Lib? `ItemStack.getRecipeRemainder()` is implemented by Fabric API.

**Comment by ChrysanthCow** [comment]
> What does this have to do with Porting Lib? `ItemStack.getRecipeRemainder()` is implemented by Fabric API.

Yes, that is the case, but the crash was exposed through Porting Lib's Recipe Book API being used by both of the two mods in question. I'm genuinely really unsure what's going on here though.

Crayfish fixed it by removing the usage of that module, but ideally, we figure out what's going on.

**Comment by TropheusJ** [comment]
This doesn't have anything to do with porting lib or the recipe book api. Fabric API adds a method that the CookingPotRecipe references and it's not there somehow. I don't know how that's possible or what would cause it, but porting lib isn't involved.

**Comment by ChrysanthCow** [comment]
I'm going to guess that it's actually linked to this issue.
https://github.com/MehVahdJukaar/FarmersDelightRefabricated/issues/77

A recipe book library that's decoupled from enums might be in order on my end.

**Comment by ChrysanthCow** [comment]
Still, not your issue. You are correct.

**Comment by TropheusJ** [comment]
That issue looks correct
