### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by Omarforce** [Fabricators-of-Create/Porting-Lib#121]
when is the 1.21 update going to release as there are various mods waiting

**Comment by Omarforce** [comment]
is the page dead?

**Comment by IThundxr** [comment]
1.21 is in the works https://github.com/Fabricators-of-Create/Porting-Lib/tree/1.21

**Comment by Omarforce** [comment]
do you have any idea regarding ETA

**Comment by IThundxr** [comment]
There's no ETA's, but it is in the works
