### ISSUE TITLE
[1.20.1] Porting Lib causes some diagonal texture blocks to be too dark

### ISSUE THREAD

**Issue by TelepathicGrunt** [Fabricators-of-Create/Porting-Lib#124]
See my Bumblezone's candle flame being too dark. And Region Unexplored's plants also being too dark. This took me a while to figure out the problem in AoF 7 modpack.

With Porting Lib:
![image](https://github.com/user-attachments/assets/0bd78101-4c92-44a3-92d3-60a4b9b57a80)

Without Porting Lib:
![image](https://github.com/user-attachments/assets/b7f22131-aa39-4d43-98ea-6f27e25f79ef)

Idk how Porting Lib is breaking the shading on our blocks but whatever it is doing, it's... wrong lol

**Comment by IThundxr** [comment]
This sounds like https://github.com/Fabricators-of-Create/Create/issues/1259

**Comment by TelepathicGrunt** [comment]
I did not have create on. I only had Porting Lib. Enabling and disabling Porting Lib *alone* causes and stops the issue
![image](https://github.com/user-attachments/assets/14c99c9c-8817-4f6b-b66a-8fd9c7334e8d)

**Comment by TelepathicGrunt** [comment]
![image](https://github.com/user-attachments/assets/6f9bb49c-6357-42c1-9b23-5e6b95f2bf13)
Looks like tropheus found the issue in Porting Lib

**Comment by IThundxr** [comment]
Could you give https://mvn.devos.one/#/snapshots/io/github/fabricators_of_create/Porting-Lib/models/2.3.5-beta.34+1.20.1 a try? It should be fixed with this version of the models module

**Comment by TelepathicGrunt** [comment]
that jar does seem to fix the issue
