### ISSUE TITLE
Mod Incompatibility: Origin's replace loot table

### ISSUE THREAD

**Issue by Kawatt** [Fabricators-of-Create/Porting-Lib#134]
Origin's (or rather Apoli's) Replace Loot Table Power Type will make all loot tables affected drop nothing while Porting Lib is installed

Datapack used to replicate the issue: 

[replace_loot_table_example.zip](https://github.com/user-attachments/files/17058679/replace_loot_table_example.zip)

When choosing human, it should make all blocks drop coal blocks
However, if Porting Lib is installed, all blocks will drop nothing

Versions:
- Porting Lib 2.3.4+1.20.1
- Origins 1.10.0
- Fabric API 0.92.2+1.20.1

Logs: 
[latest.log](https://github.com/user-attachments/files/17058773/latest.log)

**Comment by TropheusJ** [comment]
this should be fixed in 2.3.5
