### ISSUE TITLE
EntityInteractCallback is not ran on server if client returns an InteractionResult

### ISSUE THREAD

**Issue by PssbleTrngle** [Fabricators-of-Create/Porting-Lib#135]
Hello, this could go either ways, depending on if this is intended behavior or not, but it feels to me like a bug.
Due to the implementation of the `MultiPlayerGameModeMixin`, returning an `InteractionResult` (not null) for the `EntityInteractCallback` event on client side, will prevent the `ServerboundInteractPacket` to be send, since it returns already ([see here](https://github.com/Fabricators-of-Create/Porting-Lib/blob/05680818c0d83a3efa2fb2d5c4f8f60bb7fcfba5/modules/entity/src/main/java/io/github/fabricators_of_create/porting_lib/entity/mixin/client/MultiPlayerGameModeMixin.java#L43)). Adding a `SHIFT` by 1 would probably solve this, since it would then only return after the packet is sent.

**Comment by TropheusJ** [comment]
EntityInteractCallback was a broken combination of two forge events. It's been replaced with two new ones.
