### ISSUE TITLE
Incompatibility with Better Archery

### ISSUE THREAD

**Issue by Tempest-5ky** [Fabricators-of-Create/Porting-Lib#14]
### Describe the Bug

Game crashes on start when Create Fabric is launched alongside Better Archery.
Appears to be an incompatibility between Porting-lib and Better Archery.

Better Archery: https://www.curseforge.com/minecraft/mc-mods/better-archery

### Reproduction Steps

1. Load both mods together wit their respective dependencies
2. Observe

### Expected Result

Game launches as normal

### Crash Report or Log

https://mclo.gs/dYn7hmL

### Operating System

Windows 10

### Mod Version

0.5.0d

### Minecraft Version

1.18.2

### Other Mods

Better Archery, Fabric API.

**Comment by Bendimester23** [comment]
I am the author of the Better Archery mod and this issue is fixed. https://github.com/Bendimester23/better-fletching/issues/1
