### ISSUE TITLE
Shader incompatibility on Quilt 1.19.2

### ISSUE THREAD

**Issue by ShadowCube264** [Fabricators-of-Create/Porting-Lib#141]
Following on from #106, this still seems to be an issue. Testing with Quilt 0.26.4, Create and Requiem causes a crash, while removing either mod allows the game to load. [Crash log](https://mclo.gs/FLdYlS9)

A larger modpack caused a similar crash, though it was a different shader causing the issue: [crash log](https://mclo.gs/jmGfSaC)

**Comment by TropheusJ** [comment]
satin 1.9.0 is bundled with requiem. satin 1.9.1 fixes this issue.
