### ISSUE TITLE
Crash on preload when trying to launch Prominence II RPG: Hasturian Era

### ISSUE THREAD

**Issue by Defter250** [Fabricators-of-Create/Porting-Lib#143]
After some help with somone on their discord it seems the root of the crash is something to do with porting lib. 
Im running Arch Linux 6.12.1
[2024-11-25-1.log.gz](https://github.com/user-attachments/files/17910082/2024-11-25-1.log.gz)

**Comment by TropheusJ** [comment]
the only fatal error here is caused by necronomicon

**Comment by Defter250** [comment]
that may have been the incorrect log https://mclo.gs/QMWlfWe does this one provide any further insight

**Comment by TropheusJ** [comment]
Not porting lib's fault. Some mod is loading a minecraft class way too early, looks like better trims. But I can't find the class that's being blamed (`BetterTrimsPreLaunch`) on github or in the mod decompiled, so I have no idea what's going on with that.

**Comment by TropheusJ** [comment]
Found it. You're using a version that's 3 months old, the class that causes this has been removed since.

**Comment by Defter250** [comment]
I updated better trims and now this happens 
[latest.log](https://github.com/user-attachments/files/17911736/latest.log)

**Comment by Defter250** [comment]
if you need me to take this somewhere else I understand

**Comment by TropheusJ** [comment]
this is the necronomicon crash.

**Comment by Defter250** [comment]
Im sorry that was the wrong one https://mclo.gs/1IzeGgb 
Ive been fighting with for a day or so

**Comment by TropheusJ** [comment]
same problem, this time caused by additionalentityattributes
