### ISSUE TITLE
Sinytra Connector Crash

### ISSUE THREAD

**Issue by Phiro811** [Fabricators-of-Create/Porting-Lib#144]
If you run the mod with Sinytra Connecot you will face this Error:

Connector: Error transforming jar

java.utiil.concurrent.ExecutionException: java.lang.RuntimeException: Failed to execute task io/github/fabricators_of_create/porting_lib/mixin/common/ServerPlayerGameModemixin.class

**Comment by Phiro811** [comment]
![Screenshot 2024-12-01 210954](https://github.com/user-attachments/assets/6a7cea6a-abac-4cc4-aeeb-8352222d4ba1)

**Comment by IThundxr** [comment]
This should be reported to connector

**Comment by Phiro811** [comment]
but the 1.20.1 version isn't supportet anymore :(

**Comment by TropheusJ** [comment]
Porting Lib is a library for porting Forge mods to Fabric. If you’re tying to use it with connector, you’re probably doing something wrong.
Whatever mod you need it for probably has a forge version.

**Comment by Phiro811** [comment]
I'm currendly a bit late for answering but I want Effective to work and it isnt because of an porting lib error and if you are simply not using porting lib, the same error whil apear, cause of the Effective mod.
