### ISSUE TITLE
Game crashed while playing.

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [Fabricators-of-Create/Porting-Lib#150]
Game crash log. 
https://pastebin.com/aXn75dNe

**Comment by Cr4fTJuNkiE** [comment]
Crashes while trying to open my inventory.

**Comment by ChrysanthCow** [comment]
Mhm, this is a mixin failure.
I'll make a PR to fix this, and bring it over to Farmer's Delight Refabricated ASAP.

**Comment by Cr4fTJuNkiE** [comment]
Awesome! thanks so much!

**Comment by ChrysanthCow** [comment]
Okay, so the actual issue is that there's unfinished and commented out code within Porting Lib.
However, they forgot to comment out one final thing.

**Comment by Cr4fTJuNkiE** [comment]
So it's an easy fix then? I know zero about making mods, apologies.

**Comment by ChrysanthCow** [comment]
Yup, easy fix.

**Comment by Cr4fTJuNkiE** [comment]
Great!

**Comment by Cr4fTJuNkiE** [comment]
Looks like the build failed?

**Comment by ChrysanthCow** [comment]
?

Pls report with logs on Farmer's Delight Refabricated's repo if you're having gameplay issues

**Comment by ChrysanthCow** [comment]
If you're talking about the PR, it shouldnt affect actual gameplay. Its just a github check.

**Comment by Cr4fTJuNkiE** [comment]
Ahh okay. Just tried the update. No issues! Thanks again!
