### ISSUE TITLE
ExplosionEvents.DETONATE doesn't seem to work

### ISSUE THREAD

**Issue by kleiders3010** [Fabricators-of-Create/Porting-Lib#17]
When trying to use the Explosion Event (Other events do work normally), DETONATE doesn't ever seem to work, as no explosion seems to be able to trigger it

`	public ExplosionHappened() {
		ExplosionEvents.DETONATE.register((world, explosion, list, diameter) -> {
			PortinglibtestMod.LOGGER.info("egg");
		});
	}
`

**Comment by kleiders3010** [comment]
(Same issue seems to happen with BlockBreak event, as doing this doesn't do anything:
```java
	public TheBlockBroke() {
		BlockEvents.BLOCK_BREAK.register((event) -> {
			PortinglibtestMod.LOGGER.info("egg");
		});
	}
```
Doing the same on FALL event works fine

**Comment by AlphaMode** [comment]
Fixed in latest commit
