### ISSUE TITLE
Cannot getWorld or getState from BlockEvents Left_Click_Block

### ISSUE THREAD

**Issue by kleiders3010** [Fabricators-of-Create/Porting-Lib#19]
https://github.com/Fabricators-of-Create/Porting-Lib/blob/1.19.2/base/src/main/java/io/github/fabricators_of_create/porting_lib/event/common/BlockEvents.java
Seems like LEFT_CLICK_BLOCK doesn't extend BlockEvents, so you can't use event.getWorld() or event.getState() like how you would with break event

**Comment by AlphaMode** [comment]
This is fixed. It was never suppose to be a Block Event. It has been moved to PlayerInteractionEvents#LEFT_CLICK_BLOCK. Although you should use AttackBlockCallback were applicable.
