### ISSUE TITLE
ItemExtensions "createEntity" doesn't work properly, and works only inside specific instances

### ISSUE THREAD

**Issue by kleiders3010** [Fabricators-of-Create/Porting-Lib#20]
Interface: io.github.fabricators_of_create.porting_lib.extensions.ItemExntensions

It only seems to work when the stack in hand has more than 1 item on it. In every test, ONLY when having more than 1 item in the itemstack, the result was that the egg item was spawned. Neither print nor the logger nor the zombie did anything; In all tests, only the egg spawning worked.

The Two issues are:
1. Only certain things are executed, since loggers and print didn't work (They work in the rest of the mod)
2. The method only triggers when you drop the item AND you have at least 1 more remaining item in your hand of that type.

Test 1:
```java
@Override
	public Entity createEntity(Level level, Entity entity, ItemStack itemstack) {
		System.out.print("aaaaaa");
		FitestMod.LOGGER.info("aaa");
		if (!level.isClientSide()) {
			ItemEntity entityToSpawn = new ItemEntity(level, entity.getX(), entity.getY(), entity.getZ(), new ItemStack(Items.EGG));
			entityToSpawn.setPickUpDelay(100);
			level.addFreshEntity(entityToSpawn);
		}
		return null;
	}
```

Test 2:
```java
	@Override
	public Entity createEntity(Level level, Entity entity, ItemStack itemstack) {
		System.out.print("aaaaaa");
		FitestMod.LOGGER.info("aaa");
		if (!level.isClientSide()) {
			ItemEntity entityToSpawn = new ItemEntity(level, entity.getX(), entity.getY(), entity.getZ(), new ItemStack(Items.EGG));
			entityToSpawn.setPickUpDelay(100);
			level.addFreshEntity(entityToSpawn);
		}
		return new Zombie(EntityType.ZOMBIE, level);

	}
```

**Comment by TropheusJ** [comment]
This API is pretty much impossible to implement in a safe way. I am planning to just remove it.
