### ISSUE TITLE
Compound "PlayerPersisted" Only gets created after the player has died and respawned once.

### ISSUE THREAD

**Issue by kleiders3010** [Fabricators-of-Create/Porting-Lib#22]
If you do entity.getExtraCustomData().getCompound("PlayerPersisted").putBoolean("tagName", (true)); nothing will happen unless the player has respawned at least once. Seems like Compound "PlayerPersisted" only exists after respawn

**Comment by TropheusJ** [comment]
there's no reason to store an empty unused tag. If it doesn't exist, add it.

**Comment by kleiders3010** [comment]
That doesn't make sense; If the player respawns, the empty tag gets added anyway, and you print PlayerPersisted{} even if you didn't add anything to it; So the empty tag is being added anyway

**Comment by TropheusJ** [comment]
I see, getCompound will create a new one if there isn't one. Will fix when I get a chance.
note: that created tag is *not* added to the one you get it from, so that code you provided will only save anything if PlayerPersisted was already present.

**Comment by kleiders3010** [comment]
Yeah, I assumed it was supposed to generate automatically since the previous time I used it it already was; I already corrected the mods I was using it in to add the tag if it's not present, thank you!
