### ISSUE TITLE
Conflicting mixins with ImmediatelyFast

### ISSUE THREAD

**Issue by RaphiMC** [Fabricators-of-Create/Porting-Lib#25]
There is a mixins conflict in the MapRendererMapInstanceMixin class of the Porting-Lib mod and my mixin: https://github.com/RaphiMC/ImmediatelyFast/blob/main/src/main/java/net/raphimc/immediatelyfast/injection/mixins/map_atlas_generation/MixinMapRenderer_MapTexture.java. The cause is the extensive use of the local variable table inside the injections of Porting-Lib. This causes minecraft to crash if any other mod changes the `draw` methods code slightly.

Linked issue: https://github.com/RaphiMC/ImmediatelyFast/issues/11

**Comment by RaphiMC** [comment]
Changing the priority of this mod's mixin (To like 900) could probably resolve the issue because it would get injected as the first mixin then and would still have an intact local variable table at that point

**Comment by RaphiMC** [comment]
Can confirm. Changing the mixins priority of my mod to 1100 (Which means it gets applied after other mixins) resolves the crash. Due to the nature of the fragile injection of Porting-Lib I think the better solution is to fix it here instead of my mod because other mods which modify anything in the map rendering code would also crash if its not fixed here

**Comment by TropheusJ** [comment]
The target bit of code there is abysmal so making this inject any better is extremely difficult. I've lowered the priority so it applies earlier to minimize problems with it.
