### ISSUE TITLE
[1.19.2] SpawnDROPTails crash

### ISSUE THREAD

**Issue by itsdinkd** [Fabricators-of-Create/Porting-Lib#29]
Happens several times when exploring nether and overworld on certain modded blocks or at least that what it shows in the stacktrace. here are two crash reports for this example

**porting_lib: Porting Lib 2.1.706+1.19.2**

https://gist.github.com/itsdinkd/40d8679d1ef2e9d28f267cc28d2c9343
https://gist.github.com/itsdinkd/1f12413f6591fa4857bf9b23c2d34799

**Comment by itsdinkd** [comment]
![image](https://user-images.githubusercontent.com/35115304/212821665-ef12ad3e-3e7d-4d24-ba0a-6f45402612fd.png)
All the crashes here under 80kb are from this spawndroptails however the stack trace has 1 line different every time and that is when it mentions an entity. it happened from Origins, Bewitchment, Sprout, etc etc. almost any mod that has an entity. 

This has been going on for days now

**Comment by AlphaMode** [comment]
Maybe a possible mod conflict? I can add a null check to hopefully fix the crash but might cause underlining issues with the mods using the hook

**Comment by AlphaMode** [comment]
Ah I think I see the issue, could you try the latest build? When it finishes?

**Comment by itsdinkd** [comment]
> Ah I think I see the issue, could you try the latest build? When it finishes?

Launched server and unfortunately it crashed.

https://pastebin.com/hKCYFrCT

**Comment by AlphaMode** [comment]
Seems like create doesn't like the latest porting lib versions. Will see why this is

**Comment by itsdinkd** [comment]
> Seems like create doesn't like the latest porting lib versions. Will see why this is

Hi Alpha, were you able to look into why create isn't liking the latest version by chance?

**Comment by itsdinkd** [comment]
Was this by chance fixed in creates latest version?

**Comment by ExDrill** [comment]
I'm here from the mod FogLooksGoodNow, as it internally uses the library and I've figured out the specifics that lead to crash. The mob has to be a baby that's cause of death either did not have a direct entity or the direct entity wasn't a player/living entity. Both fall damage and arrow cause crashes, while a melee attack does not. Hope this helps!

**Comment by TropheusJ** [comment]
this should be fixed
