### ISSUE TITLE
Adding 1.18.2 `porting-lib` dependency to my fabric project doesn't work

### ISSUE THREAD

**Issue by izofar** [Fabricators-of-Create/Porting-Lib#40]
**My Setup:**
In my `build.gradle` under the `dependencies` tag I have: `modImplementation(include("io.github.fabricators_of_create.Porting-Lib:porting-lib:${portinglib_version}"))`

In my `gradle.properties` I have: `portinglib_version = 1.2.783-beta+1.18.2` as directed by your `README.md`

**Error:**
My gradle refresh output gives: `Could not GET 'https://jitpack.io/io/github/fabricators_of_create/Porting-Lib/porting-lib/1.2.783-beta+1.18.2/porting-lib-1.2.783-beta+1.18.2.pom'. Received status code 400 from server: Bad Request
Disable Gradle 'offline mode' and sync project`

Did I misunderstand the README, or is 1.18.2 not supported yet?

**Comment by AlphaMode** [comment]
The dependency for 1.18.2 is ""io.github.fabricators_of_create:Porting-Lib:$port_lib_version+$minecraft_version""

**Comment by izofar** [comment]
This worked, thank you.
