### ISSUE TITLE
Random Server Crashes

### ISSUE THREAD

**Issue by instinxx** [Fabricators-of-Create/Porting-Lib#42]
Im getting multiple random server crashes. Seems to be cause by players loading chunks.

[crash-2023-03-06_17.23.40-server.txt](https://github.com/Fabricators-of-Create/Porting-Lib/files/10909784/crash-2023-03-06_17.23.40-server.txt)

Minecraft Version: 1.19.2
fabricloader: Fabric Loader 0.14.17
create: Create 0.5.0.i-961+1.19.2
Porting Lib 2.1.784+1.19.2

**Comment by instinxx** [comment]
@MissPotato, by any chance did you use a pregenerator on your world?

**Comment by MissPotato** [comment]
I did not.

**Comment by TropheusJ** [comment]
closing in favor of #43
