### ISSUE TITLE
[1.18.2] Step height attribute doesn't work

### ISSUE THREAD

**Issue by KonSola5** [Fabricators-of-Create/Porting-Lib#44]
"porting_lib:stepHeight" does not add any additional step height.

Fixing this would fix this Hephaestus' issue:
[https://github.com/Alpha-s-Stuff/TinkersConstruct/issues/44](https://github.com/Alpha-s-Stuff/TinkersConstruct/issues/44)

**Comment by AlphaMode** [comment]
This was fixed in later versions of porting lib
