### ISSUE TITLE
Compatiblity with stepheightentityattribute:stepheight

### ISSUE THREAD

**Issue by florensie** [Fabricators-of-Create/Porting-Lib#45]
There already existed a step height EAM for Fabric. Perhaps it's possible to make them compatible by somehow making `stepheightentityattribute:stepheight` an alias for the one in porting lib?

https://github.com/emilyploszaj/step-height-entity-attribute

**Comment by AlphaMode** [comment]
Registry aliases aren't a thing and seem unsafe. What would even be the benefit here?

**Comment by florensie** [comment]
I haven't properly tested yet, but there might be some inconsistencies in the order the attributes are applied. It wouldn't be an issue if mods only use addition, but multiplication might be a problem.

I know registry aliases aren't a thing, but I thought it would be worth investigating. I can look further into it this weekend.

**Comment by AlphaMode** [comment]
Closing this as not planned
