### ISSUE TITLE
Global loot modifiers don't work on entities

### ISSUE THREAD

**Issue by ochotonida** [Fabricators-of-Create/Porting-Lib#46]
Loot modifiers are not applied on loot dropped from entities. As far as I can tell this is because `LivingEntity.dropFromLootTable` calls the wrong overload of `LootTable.getRandomItems`. Forge patches `LivingEntity` such that it calls `getRandomItems(LootContext)` rather than `getRandomItems(LootContext, Consumer<ItemStack>)`, as loot modifiers don't get applied in the latter.

**Comment by AlphaMode** [comment]
What version are you on?

**Comment by ochotonida** [comment]
Minecraft 1.19.4, Porting Lib 2.1.917

**Comment by AlphaMode** [comment]
Ah, I see I had fixed this a while ago but I guess I never pushed my changes

**Comment by AlphaMode** [comment]
The latest commit should fix it, hopefully it doesn't cause any compatibility issues with other mods
