### ISSUE TITLE
Compat issue with immersive portals

### ISSUE THREAD

**Issue by Sunconure11** [Fabricators-of-Create/Porting-Lib#48]
https://pastebin.com/YUyLHEub

https://pastebin.com/9c9g3j67

**Comment by Sunconure11** [comment]
https://github.com/iPortalTeam/ImmersivePortalsMod/issues/1353

**Comment by AlphaMode** [comment]
The log doesn't mention porting lib at all. Have you tried testing this with just QSL? Porting Lib doesn't touch the CustomPayloadS2CPacket class at all

**Comment by Sunconure11** [comment]
Actually, it does mention porting lib.

https://github.com/Fabricators-of-Create/Porting-Lib/tree/1.19.2/networking/src/main/java/me/pepperbell

The class for pepperbell is being mentioned.

**Comment by AlphaMode** [comment]
Yes but thats just using fabric api, so I'm assuming this might be a problem with QSL

**Comment by Sunconure11** [comment]
Immersive Portals has always mentioned it has some kind of error with Create if you load the two together, and it will display this message in game.

[latest(6).log](https://github.com/Fabricators-of-Create/Porting-Lib/files/11492940/latest.6.log)

Here is the associated latest log.

**Comment by AlphaMode** [comment]
Yes, I am aware. I'm just wondering how the current error is related.

**Comment by TropheusJ** [comment]
The first crash definitely has nothing to do with Porting Lib. It's an immersive portals mixin to CustomPayloadS2CPacket failing, and we do not touch that. Another mod is removing its target.
The second one appears to be the same as the first one, triggered from a different place.

**Comment by Sunconure11** [comment]
Some slight research leads me to this, which I do have all of said mods, barring connectivity.

https://github.com/someaddons/connectivity/issues/69
