### ISSUE TITLE
FluidStack missing equals() implementation

### ISSUE THREAD

**Issue by mspielberg** [Fabricators-of-Create/Porting-Lib#50]
The Forge version of FluidStack has an [implementation of Object.equals()](https://github.com/MinecraftForge/MinecraftForge/blob/1.19.x/src/main/java/net/minecraftforge/fluids/FluidStack.java#L324-L338), but Porting-Lib does not, continuing to use the default of reference equality. As noted in the Forge code, this is important when FluidStack is used in standard data structures.

As an example of where this causes a problem, Tinker's Construct [uses a HashMap to cache models keyed by FluidStack](https://github.com/SlimeKnights/TinkersConstruct/blob/1.18.2/src/main/java/slimeknights/tconstruct/smeltery/client/CopperCanModel.java#L178). Because of the missing equals(), every instance of FluidStack is considered to be unequal to every other instance, and the cache grows without bound. On my install using [Hephaestus](https://github.com/Alpha-s-Stuff/TinkersConstruct), the cache grows to 500k+ entries, taking up over 2.5 GB of RAM before finally crashing.

**Comment by AlphaMode** [comment]
Fixed, thanks for noticing this
