### ISSUE TITLE
`TransferUtils.getNonEmpty` doesn't respect storage with a non-blank resource that contain no resources

### ISSUE THREAD

**Issue by MattiDragon** [Fabricators-of-Create/Porting-Lib#53]
In my mod, extended drawer, storages can be locked so that their resource type never changes even if they run out of items. This causes issues as create assumes it can remove items from the storage when in fact it's empty. I don't know why create doesn't gracefully fail when it can't extract the required items, but the root cause it that you don't handle that case here in porting lib.

Your code to get all the non-empty views of a storage in `TransferUtils.getNonEmpty` doesn't check the count, even though it's the best indicator of fill level. I assume this wasn't intentional. If it was then I can open an issues on the create fabric repo about this. 

Originally reported here: https://github.com/MattiDragon/ExtendedDrawers/issues/66#issuecomment-1596380406
Crash report from original reporter: https://pastebin.com/ZLtehkLS

**Comment by TropheusJ** [comment]
I think an amount of 0 is supposed to make isResourceBlank true. An itemstack with a count of 0 is empty, despite still having an item.

**Comment by MattiDragon** [comment]
According to Technici4n, the primary author of the transfer api, my storage is following the spec. See this conversation in the fabric discord server: https://discord.com/channels/507304429255393322/566417932503089232/1120618010529505320

**Comment by Noaaan** [comment]
I believe Toolboxes do this (maybe not technically, but at least visually). It will show a resource with a count of 0 unless you clear it if you add and pull out items from it

**Comment by TropheusJ** [comment]
seems FAPI filters by count too.

**Comment by TropheusJ** [comment]
fixed on 1.18, will be ported up eventually
