### ISSUE TITLE
Global loot modifiers don't work on entities

### ISSUE THREAD

**Issue by ochotonida** [Fabricators-of-Create/Porting-Lib#54]
Porting Lib version 2.1.1044
Minecraft 1.20.1

Global loot modifiers are not applied on loot from killed entities. For block drops, chest loot etc. they work as intended.
Likely related to https://github.com/MinecraftForge/MinecraftForge/issues/9551.

**Comment by TropheusJ** [comment]
maybe because of #56, it looks like it should be fine

**Comment by ochotonida** [comment]
I'm still having this issue when using the latest release for 1.20 (version 2.1.1093), would you mind taking another look? Keep in mind this issue only applies to entities, and only appears to affect the 1.20 versions of Porting Lib.

**Comment by TropheusJ** [comment]
was looking at a different branch. *now* everything should be good.

**Comment by ochotonida** [comment]
Thanks! it's working now

**Comment by ochotonida** [comment]
The fix for this issue may have had an unintentional side effect. Because loot modifiers are applied on any call to `LootTable::getRandomItemsRaw`, it's now possible for loot modifiers to be applied multiple times while loot is generated.
Forge applies loot modifiers on `getRandomItems` rather than `getRandomItemsRaw`, such that loot tables that reference other loot tables only apply loot modifiers for the top level loot table.
Additionally, if a loot modifier generates loot from a loot table using `getRandomItemsRaw`, this can lead to a StackOverflowError
