### ISSUE TITLE
ExpandFmjTask doesn't add mixins and aw in 1.19.2

### ISSUE THREAD

**Issue by Linguardium** [Fabricators-of-Create/Porting-Lib#56]
the changes in commit c4b8dc4 were never applied to 1.19.2.

This is causing an issue where the built loot module was designed for automatic mixin inclusion but the automatic process doesnt exist (leading to no loot module mixins being applied in 1.19.2)

**Comment by TropheusJ** [comment]
this seems to have been fixed
