### ISSUE TITLE
crashes with creolib

### ISSUE THREAD

**Issue by nickademas** [Fabricators-of-Create/Porting-Lib#60]
[latest.log](https://github.com/Fabricators-of-Create/Porting-Lib/files/12403698/latest.log)

**Comment by AlphaMode** [comment]
This was already fixed your using a outdated version

**Comment by AlphaMode** [comment]
Actually this might be something else

**Comment by AlphaMode** [comment]
Looking into this further; this is honestly creolibs fault for not using rea and existing attribute mods
