### ISSUE TITLE
Possible compat issue with this and Botania

### ISSUE THREAD

**Issue by Sunconure11** [Fabricators-of-Create/Porting-Lib#61]
https://github.com/CorgiTaco/Enhanced-Celestials/issues/175

Note: Hard to replicate, as it only happens with certain combos of mods and I'm not sure why.

**Comment by Sunconure11** [comment]
https://github.com/Fabricators-of-Create/Porting-Lib/blob/1.19.2/base/src/main/java/io/github/fabricators_of_create/porting_lib/mixin/client/LevelRendererMixin.java

This class seems somewhat suspect.

**Comment by TropheusJ** [comment]
ModifyVariable has a tendency to break when other mixins target the same general area. It should be fine if botania’s applies earlier (set priority to like 800)

**Comment by Sunconure11** [comment]
Could you look at Enhanced Celestials and see if there is something there? This bug is absurdly hard to actually... get it to occur.

**Comment by TropheusJ** [comment]
Almost definitely [this redirect](https://github.com/CorgiTaco/Enhanced-Celestials/blob/1.20.X/Common/src/main/java/corgitaco/enhancedcelestials/mixin/client/MixinWorldRenderer.java)

**Comment by Sunconure11** [comment]
@corgitaco
