### ISSUE TITLE
Particles when slimes jump are not rendered

### ISSUE THREAD

**Issue by Lolothepro** [Fabricators-of-Create/Porting-Lib#66]
https://github.com/Fabricators-of-Create/Porting-Lib/assets/68275908/97fee337-d507-461f-84a3-d8af8e9469d5

**Comment by AlphaMode** [comment]
Fixed in https://github.com/Fabricators-of-Create/Porting-Lib/commit/cd4f2f2be23a992fbe8de3554c259ea1cd61ecc1
