### ISSUE TITLE
RenderTargetMixin's stencil buffer override is redundant and crashy

### ISSUE THREAD

**Issue by ds84182** [Fabricators-of-Create/Porting-Lib#69]
I don't see a reason why it's being overridden. Minecraft already has proper support for stencil buffers, including fallback code paths to avoid using unsupported attachment formats.

This mixin is the root cause of Create-related crashes when using Holy GL4ES.

**Comment by TropheusJ** [comment]
I am not a graphics person, the stencil code is pretty much directly from forge, and is required for Create to function.
I'm not interested in supporting weird OpenGL replacements either.

**Comment by TropheusJ** [comment]
PRs are always welcome, if this can be fixed without breaking compatibility.
