### ISSUE TITLE
Porting Lib's TagUtil redirects Netherite to a wrong tag

### ISSUE THREAD

**Issue by KonSola5** [Fabricators-of-Create/Porting-Lib#70]
https://github.com/Fabricators-of-Create/Porting-Lib/blob/f47f7d727241a08694bfccd144edfb185e2f27c6/base/src/main/java/io/github/fabricators_of_create/porting_lib/util/TagUtil.java#L38

Fabric has a convention for higher mining levels, that being `#fabric:needs_tool_level_x`, where `x` is a tier number.

So in this case, the switch should say:
`case NETHERITE -> new ResourceLocation("fabric:needs_tool_level_4")`
(or a reference to said identifier in another class).

Fixing this would fix https://github.com/Alpha-s-Stuff/TinkersConstruct/issues/81 in Hephaestus.

**Comment by KonSola5** [comment]
https://github.com/Fabricators-of-Create/Porting-Lib/blob/f47f7d727241a08694bfccd144edfb185e2f27c6/base/src/main/java/io/github/fabricators_of_create/porting_lib/util/TierSortingRegistry.java#L186

You might also want to include fallback for tiers 4 and higher in the `isCorrectTierVanilla`, since `#fabric:needs_tool_level_x` are honored for `x` tier.

**Comment by KonSola5** [comment]
https://github.com/FabricMC/fabric/blob/dc89771ba2df08038e77d8f80289203986785864/fabric-mining-level-api-v1/src/main/java/net/fabricmc/fabric/api/mininglevel/v1/MiningLevelManager.java
This class will save you a ton of trouble with the tiers.

**Comment by TropheusJ** [comment]
probably fixed on 1.19, will be cherrypicked to 1.20, 1.18 needs a fix in ForgeTags

**Comment by TropheusJ** [comment]
this is hopefully fixed on all versions now
