### ISSUE TITLE
Mixins causing incompatibility with DashLoader

### ISSUE THREAD

**Issue by acanthii** [Fabricators-of-Create/Porting-Lib#73]
DashLoader currently crashes trying to initialize a Transformation because it passes in the standard 3 Vec3f's, when Porting Lib makes Minecraft expect 4. I narrowed it down to ItemTransformMixin, and I believe that's what's causing it because it introduces another non-nullable variable for initialization.

```
Cause: net.minecraft.client.render.model.json.Transformation.<init>(org.joml.Vector3f,org.joml.Vector3f,org.joml.Vector3f,org.joml.Vector3f)Suggestion: Check if the constructor holds all of the fields.

Object Stacktrace:
	in Transformation_<@DataNullablenull>
	at field thirdPersonLeftHand in DashModelTransformation_<@DataNullablenull>
	at field transformation in DashBasicBakedModel
```

extensions/src/main/java/io/github/fabricators_of_create/porting_lib/extensions/mixin/client/ItemTransformMixin.java
extensions/src/main/java/io/github/fabricators_of_create/porting_lib/extensions/extensions/ItemTransformExtensions.java

**Comment by TropheusJ** [comment]
Marking the field as nullable would probably make it not crash, but dashloader would probably not deserialize extended transformations properly. I would need to look into how dashloader works to add actual compat.

**Comment by TropheusJ** [comment]
dashloader is discontinued, this won't be fixed
