### ISSUE TITLE
Loot tables are broken with CraftTweaker installed

### ISSUE THREAD

**Issue by BluSpring** [Fabricators-of-Create/Porting-Lib#77]
With the current version of Porting Lib for 1.20.1 installed alongside CraftTweaker, every single loot table stops functioning. This includes:
- Chest loot
- Mob drops
- Fishing

**Minecraft Version**: 1.20.1
**Fabric Loader Version**: 0.15.6
**Fabric API Version**: 0.91.0+1.20.1
**CraftTweaker Version**: 1.20.1-14.0.30
**Porting Lib Version**: 2.1.1178+1.20.1

[latest.log](https://github.com/Fabricators-of-Create/Porting-Lib/files/14000199/latest.log)

[An issue](https://github.com/CraftTweaker/CraftTweaker/issues/1702) has also been created on the CraftTweaker repo to bring it up to their attention too.

**Comment by TropheusJ** [comment]
almost definitely same cause as #74

**Comment by TropheusJ** [comment]
It's the same cause, but has to be a different case.

**Comment by TropheusJ** [comment]
root cause fixed.
