### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by HacoKavanah** [Fabricators-of-Create/Porting-Lib#8]
[crash-2022-05-15_15.54.14-client.txt](https://github.com/Fabricators-of-Create/Porting-Lib/files/8694978/crash-2022-05-15_15.54.14-client.txt)

**Comment by TropheusJ** [comment]
Can you try installing this version
[porting_lib-0.2.0+1.18.2.573bc92.zip](https://github.com/Fabricators-of-Create/Porting-Lib/files/8695919/porting_lib-0.2.0%2B1.18.2.573bc92.zip)

**Comment by HacoKavanah** [comment]
[crash-2022-05-16_13.51.25-server.txt](https://github.com/Fabricators-of-Create/Porting-Lib/files/8699387/crash-2022-05-16_13.51.25-server.txt)
Crash on startup-

**Comment by HacoKavanah** [comment]
Gonna try now with newest versions of both mods

**Comment by HacoKavanah** [comment]
[crash-2022-05-16_14.28.43-client.txt](https://github.com/Fabricators-of-Create/Porting-Lib/files/8699634/crash-2022-05-16_14.28.43-client.txt)
Got the original crash again, using versions:
create-mc1.18.2_v0.4.1+563
porting_lib-0.2.0+1.18.2.6970235

Do the newest versions include the fixes of 0.2.0+1.18.2.573bc92?

**Comment by AlphaMode** [comment]
remove twilight forest

**Comment by HacoKavanah** [comment]
Used the newest newest version for like an hour now, seems to work well!
