### ISSUE TITLE
Can't use Porting Lib in 1.20.2 workspace

### ISSUE THREAD

**Issue by FirEmerald** [Fabricators-of-Create/Porting-Lib#90]
the latest versions of porting lib are supposed to be for Minecraft 1.20.1 _through_ 1.20.4, but when I use one of them in a 1.20.2 fabric workspace, it doesn't launch and says Porting Lib requires Minecraft 1.20.1

**Comment by AlphaMode** [comment]
1.20.2 isn't supported

**Comment by TropheusJ** [comment]
the supported versions listed on modrinth are messed up. Porting lib is tightly linked to MC versions.
Only 1.20.1 and 1.20.4 are supported, but no versions for 1.20.4 have been released yet.

**Comment by FirEmerald** [comment]
Thanks for the clarification.
