### ISSUE TITLE
Crash between Porting Lib and Supplementaries after loading into a World

### ISSUE THREAD

**Issue by AlexTheSuprWolf** [Fabricators-of-Create/Porting-Lib#91]
world will crash shortly after being loaded into with both installed.

[crash-2024-02-29_18.02.41-server.txt](https://github.com/Fabricators-of-Create/Porting-Lib/files/14454488/crash-2024-02-29_18.02.41-server.txt)

[latest.log](https://github.com/Fabricators-of-Create/Porting-Lib/files/14454494/latest.log)

**Comment by TropheusJ** [comment]
already fixed

**Comment by AlexTheSuprWolf** [comment]
I presume by already fixed, you mean in an update that hasn't been released yet?

**Comment by TropheusJ** [comment]
yes
