### ISSUE TITLE
[Question] importing the version 1.20.1 into workspace 1.20.1

### ISSUE THREAD

**Issue by Xelbayria** [Fabricators-of-Create/Porting-Lib#95]
Hello, 
I want to gather more details about what's going on:
new version: `modImplementation(include("io.github.fabricators_of_create.Porting-Lib:2.3.0+1.20.1"))`
curseforge version: `modImplementation("curse.maven:porting-lib-696251:5167565")`
older version is: `modImplementation("io.github.fabricators_of_create.Porting-Lib:porting-lib:2.0.591+1.19.2")` 
 It was working fine (using a mod in Launcher like PrismLauncher) but it won't work with running `Minecraft Client` with Fabric in IDEA. 

are the older version and the newer version (1.20.1) similar? I imported **curseforge version** and it doesn't work. I appreciate it if anyone could help me understand what's going on.

**Comment by IThundxr** [comment]
Attach logs

**Comment by Xelbayria** [comment]
FYI, this is not a bug. just a question. 

there are too many factors I cannot determine which is a bug. 

```java
    @NotNull
    private static<T extends Block> RegistryObject<T> makeRegObj(ResourceLocation id) {
        return new RegistryObject<>(id, () ->(T) BuiltInRegistries.BLOCK.get(id), Registries.BLOCK);
    }
```
this is using the library via Porting_lib

i'll gather more information. give me a few minutes

**Comment by IThundxr** [comment]
New releases are published without a fat jar, https://mvn.devos.one/#/releases/io/github/fabricators_of_create/Porting-Lib over here in the devos releases maven, the old branch that was used for 1.20.1 was renamed into legacy and the entity refactor branch was promoted to master

**Comment by Xelbayria** [comment]
ok, i see what's going on.  what's the code to import from `mvn.devos.one`? 

i meant without the module. just version to include all of library I need into the workspace

**Comment by IThundxr** [comment]
repositories block in build.gradle
```gradle
maven { url = "https://mvn.devos.one/releases" } // Porting Lib Releases
```

build.gradle
```gradle
    for (String module in port_lib_modules.split(",")) {
        modApi(include("io.github.fabricators_of_create.Porting-Lib:$module:$port_lib_version"))
    }
```

gradle.properties
```properties
port_lib_version = 2.3.0+1.20.1
port_lib_modules = #add modules you want to use here
```

**Comment by Xelbayria** [comment]
i'll try that

**Comment by Xelbayria** [comment]
it's working. thanks for helping out.
