### ISSUE TITLE
Trident like items crash the game

### ISSUE THREAD

**Issue by macuguita** [Fabricators-of-Create/Porting-Lib#97]
Whenever I use a trident like projectile (in this case a bee stinger from the bumblezone) it sometimes crashes the game
here's the crash report:
https://mclo.gs/rnGgc7s

**Comment by TelepathicGrunt** [comment]
Pehkui might be conflicting with Porting Lib somehow on Quilt. Pehkui has a mixin into PersistentProjectileEntity's tick method where Porting Lib's failing mixin is.

https://github.com/Virtuoel/Pehkui/blob/19fdb350356f66acf00c73654cedc0313d4522ff/src/main/java/virtuoel/pehkui/mixin/PersistentProjectileEntityMixin.java#L28

Could also be coincidental and Porting Lib's mixin here is just not setup right.

**Comment by IThundxr** [comment]
> Pehkui might be conflicting with Porting Lib somehow on Quilt. Pehkui has a mixin into PersistentProjectileEntity's tick method where Porting Lib's failing mixin is.
> 
> [Virtuoel/Pehkui@`19fdb35`/src/main/java/virtuoel/pehkui/mixin/PersistentProjectileEntityMixin.java#L28](https://github.com/Virtuoel/Pehkui/blob/19fdb350356f66acf00c73654cedc0313d4522ff/src/main/java/virtuoel/pehkui/mixin/PersistentProjectileEntityMixin.java#L28)
> 
> Could also be coincidental and Porting Lib's mixin here is just not setup right.

Probably wouldn't cause this, the local ref would still be set since pehkui isn't cancelling

**Comment by TropheusJ** [comment]
the relevant code has been rewritten, this should be fixed

**Comment by circularsprojects** [comment]
I've just experienced the same issue, but I'm not sure if the version of porting lib I'm using is the one that's meant to be fixed.
Here's my crash report: https://mclo.gs/bk1XJM2

**Comment by TropheusJ** [comment]
old version

**Comment by dhouck** [comment]
So just to clarify: upgrading to 0.5.1f patch 1 will fix this?  Iʼve been putting that off because of mod compatibility with Hephaestus (which is apparently also fixed in dev but not released) but if the trident crash is fixed I might have to update anyway.

**Comment by IThundxr** [comment]
> So just to clarify: upgrading to 0.5.1f patch 1 will fix this? Iʼve been putting that off because of mod compatibility with Hephaestus (which is apparently also fixed in dev but not released) but if the trident crash is fixed I might have to update anyway.

update create to latest and install porting lib from modrinth/curseforge to fix the hephaestus problem

**Comment by dhouck** [comment]
Oh, huh, I didn’t realize that worked; I thought it wasnʼt useful to think about that for non-devs because it was bundled into Create.  Iʼll have to try that later.
