### ISSUE TITLE
Incompatible with quilt fabric library version

### ISSUE THREAD

**Issue by ABSOLUTEMAX123** [Fabricators-of-Create/Porting-Lib#99]
when loading a quilt profile, porting lib reports "porting-lib requires version 0.77.0 of fabric, but 0.76.0 is present". however, as the quilt loader version only is up to 0.76.0 in terms of fabric, and there is no version of porting lib that is available for 1.19.2 that is compatible with that fabric version

**Comment by blicko** [comment]
I'm having the same issue, How did you fix it?
